name: Continuous Integration

on: push

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev', 'master' (or 'main')
      - name: 'Flutter Version'
        run: flutter --version
      - name: Install
        run: |
          flutter config --enable-web
          flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Build
        run: cd example && flutter build android